#! /bin/sh
# /etc/init.d/rpyc_server
#

case "$1" in
  start)
    /bin/rpyc_server.py
    ;;
  stop)
    
    ;;
  *)
    echo "Usage: /etc/init.d/rpyc_server {start|stop}"
    exit 1
    ;;
esac

exit 0


